### PR TITLE
re-enable script for readarr

### PR DESCRIPTION
**Pull request by stavros-k**
Script was disabled here for testing 5d5ea817a83b9afe9b09d189472c3dc56db5cb79
Then the actual fix was the user which was fixed here e2be2eae7a73cbf420d132f91a0aac697adb7ecf

Uncommenting the script with the hope that it doesn't need anything else for it to work!

### CODE REVIEW

**Comment by funkypenguin** [comment]
Thanks @stavros-k :) The script was disabled because it seems as if the syntax for the Readarr .xml file has changed recently - do you know whether readarr still works if you re-enable this?

**Comment by stavros-k** [comment]
I've let the Readar create the config it self.

```xml
<Config>
  <BindAddress>*</BindAddress>
  <Port>8787</Port>
  <SslPort>6868</SslPort>
  <EnableSsl>False</EnableSsl>
  <LaunchBrowser>True</LaunchBrowser>
  <ApiKey>c1a82f0be9af4ccda835b1b54d7beef0</ApiKey>
  <AuthenticationMethod>None</AuthenticationMethod>
  <AuthenticationRequired>Enabled</AuthenticationRequired>
  <Branch>develop</Branch>
  <LogLevel>debug</LogLevel>
  <SslCertPath></SslCertPath>
  <SslCertPassword></SslCertPassword>
  <UrlBase></UrlBase>
  <InstanceName>Readarr</InstanceName>
  <UpdateMechanism>Docker</UpdateMechanism>
</Config>
```

But even tho I've started it like this

```sh
146d784b6e12:/config$ /app/bin/Readarr --nobrowser --data /config
[Info] Bootstrap: Starting Readarr - /app/bin/Readarr - Version 0.4.0.2634
....
[Info] Microsoft.Hosting.Lifetime: Content root path: /config
```

I found the config created at `/home/elfie/.config/Readarr/config.xml` 
Not sure if it first checks at `/config`

It is something with the authentication required.
I did try to look into the code, but C#'s framework these days do too much abstractions and I'm not familiar :D

```sh
[v0.4.0.2634] System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentException: Must specify valid information for parsing in the string. (Parameter 'value')
   at System.Enum.TryParse(Type enumType, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, Object& result)
   at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
   at NzbDrone.Core.Configuration.ConfigFileProvider.GetValueEnum[T](String key, T defaultValue, Boolean persist) in ./Readarr.Core/Configuration/ConfigFileProvider.cs:line 285
   at NzbDrone.Core.Configuration.ConfigFileProvider.get_AuthenticationRequired() in ./Readarr.Core/Configuration/ConfigFileProvider.cs:line 213
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at NzbDrone.Core.Configuration.ConfigFileProvider.GetConfigDictionary() in ./Readarr.Core/Configuration/ConfigFileProvider.cs:line 116
   at NzbDrone.Core.Configuration.ConfigFileProvider.SaveConfigDictionary(Dictionary`2 configValues) in ./Readarr.Core/Configuration/ConfigFileProvider.cs:line 126
   at NzbDrone.Core.Update.UpdaterConfigProvider.ChangeUpdateMechanism(UpdateMechanism updateMechanism) in ./Readarr.Core/Update/ConfigureUpdateMechanism.cs:line 68
   at NzbDrone.Core.Update.UpdaterConfigProvider.Handle(ApplicationStartedEvent message) in ./Readarr.Core/Update/ConfigureUpdateMechanism.cs:line 45
   at NzbDrone.Core.Messaging.Events.EventAggregator.PublishEvent[TEvent](TEvent event)
```

---

I've also noticed that `xmlstarlet` is not available?!

```sh
c428c7947eac:/config$ xmlstarlet
bash: xmlstarlet: command not found
```

That's all I could find for now

**Comment by swensorm** [comment]
It ended up being a bit involved to trace down every issue to get this running again for both new and existing installations so I created a new PR with all the changes rather than a long explanation and list.

https://github.com/elfhosted/containers/pull/613

**Comment by stavros-k** [comment]
@swensorm Thanks, I'll close this one! Nice tracking!

**Pull request closed without merging**
